"""
EQ Preset Generator for HQPlayer Matrix Processor.

Generates parametric EQ files in Room EQ Wizard (REW) text format
that can be loaded into HQPlayer's Matrix Processor via Browse button.

Also generates HQPlayer inline plugin syntax for reference.

Supported filter types:
  - PK  (peak/parametric)   → iir:peak;f=FREQ;g=GAIN;q=Q
  - LSC (low shelf)         → iir:lshelf;f=FREQ;g=GAIN;s=SLOPE
  - HSC (high shelf)        → iir:hshelf;f=FREQ;g=GAIN;s=SLOPE
  - HP  (high pass)         → iir:hp;f=FREQ;q=Q
  - LP  (low pass)          → iir:lp;f=FREQ;q=Q
  - NO  (notch)             → iir:notch;f=FREQ;q=Q
"""

import json
import logging
import os
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

# Directory for generated EQ files
EQ_OUTPUT_DIR = Path(os.environ.get("EQ_OUTPUT_DIR", "/app/generated_eq"))

# REW filter type codes
REW_FILTER_TYPES = {
    "peak": "PK",
    "pk": "PK",
    "lowshelf": "LSC",
    "lshelf": "LSC",
    "lsc": "LSC",
    "highshelf": "HSC",
    "hshelf": "HSC",
    "hsc": "HSC",
    "highpass": "HP",
    "hp": "HP",
    "lowpass": "LP",
    "lp": "LP",
    "notch": "NO",
    "no": "NO",
    "allpass": "AP",
    "ap": "AP",
    "bandpass": "BP",
    "bp": "BP",
}

# HQPlayer iir plugin type mapping
HQP_IIR_TYPES = {
    "PK": "peak",
    "LSC": "lshelf",
    "HSC": "hshelf",
    "HP": "hp",
    "LP": "lp",
    "NO": "notch",
    "AP": "ap",
    "BP": "bp",
}


def _normalize_filter_type(filter_type: str) -> str:
    """Normalize filter type string to REW code."""
    key = filter_type.lower().replace("-", "").replace("_", "").replace(" ", "")
    code = REW_FILTER_TYPES.get(key)
    if not code:
        raise ValueError(
            f"Unknown filter type '{filter_type}'. "
            f"Supported: peak, lowshelf/lshelf, highshelf/hshelf, highpass/hp, lowpass/lp, notch, allpass, bandpass"
        )
    return code


def generate_rew_text(
    filters: list[dict[str, Any]],
    name: str = "Sautium EQ",
    notes: str = "",
) -> str:
    """
    Generate Room EQ Wizard format text from filter parameters.

    Args:
        filters: List of filter dicts with keys:
            - type: "peak", "lowshelf", "highshelf", "highpass", "lowpass", "notch"
            - freq: Frequency in Hz
            - gain: Gain in dB (for peak, shelf filters)
            - q: Q factor (for peak, hp, lp, notch, bandpass)
            - slope: Slope (alternative to Q for shelf filters)
        name: Preset name (for header)
        notes: Optional notes

    Returns:
        REW format text string
    """
    now = datetime.now(timezone.utc).strftime("%a %b %d %H:%M:%S %Z %Y")

    lines = [
        "Filter Settings file",
        "",
        "Room EQ V5.20",
        f"Dated: {now}",
        "",
        f"Notes: {notes or f'Generated by Sautium: {name}'}",
        "",
        "Equaliser: Generic",
    ]

    for i, f in enumerate(filters, 1):
        ftype = _normalize_filter_type(f["type"])
        freq = float(f["freq"])
        gain = float(f.get("gain", 0.0))
        q = float(f.get("q", 0.707))

        # For shelf filters, use slope if provided instead of Q
        if ftype in ("LSC", "HSC") and "slope" in f:
            q = float(f["slope"])

        # Format: "Filter  1: ON  PK       Fc    6000.0 Hz  Gain  -3.0 dB  Q  5.000"
        if ftype in ("HP", "LP", "NO", "AP", "BP"):
            # These don't use Gain parameter in REW
            lines.append(
                f"Filter {i:2d}: ON  {ftype:<8s} Fc {freq:10.1f} Hz  Gain   0.0 dB  Q {q:.3f}"
            )
        else:
            lines.append(
                f"Filter {i:2d}: ON  {ftype:<8s} Fc {freq:10.1f} Hz  Gain {gain:5.1f} dB  Q {q:.3f}"
            )

    return "\n".join(lines) + "\n"


def generate_hqp_pipeline_syntax(filters: list[dict[str, Any]]) -> str:
    """
    Generate HQPlayer inline plugin syntax for Matrix Processor 'Process' field.

    Example output: "iir:peak;f=6000;g=-3;q=5,iir:hshelf;f=8500;g=-2;s=0.7"

    Args:
        filters: Same format as generate_rew_text

    Returns:
        HQPlayer pipeline syntax string
    """
    parts = []
    for f in filters:
        ftype = _normalize_filter_type(f["type"])
        hqp_type = HQP_IIR_TYPES.get(ftype, "peak")
        freq = float(f["freq"])
        gain = float(f.get("gain", 0.0))
        q = float(f.get("q", 0.707))

        params = [f"f={freq:.0f}"]

        if ftype in ("PK", "LSC", "HSC"):
            params.append(f"g={gain:.1f}")

        if ftype in ("LSC", "HSC") and "slope" in f:
            params.append(f"s={float(f['slope']):.3f}")
        else:
            params.append(f"q={q:.3f}")

        parts.append(f"iir:{hqp_type};{';'.join(params)}")

    return ",".join(parts)


def save_eq_preset(
    filters: list[dict[str, Any]],
    name: str,
    notes: str = "",
    description: str = "",
) -> dict[str, str]:
    """
    Generate and save EQ preset files.

    Args:
        filters: Filter parameters (see generate_rew_text)
        name: Preset name (used for filename)
        notes: Notes for REW file header
        description: Human-readable description of what this EQ does

    Returns:
        Dict with: rew_path, hqp_syntax, instructions
    """
    EQ_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    # Sanitize filename
    safe_name = "".join(c if c.isalnum() or c in "-_ " else "" for c in name).strip()
    safe_name = safe_name.replace(" ", "_").lower()
    if not safe_name:
        safe_name = "eq_preset"

    # Generate REW text
    rew_text = generate_rew_text(filters, name=name, notes=notes)
    rew_filename = f"{safe_name}.txt"
    rew_path = EQ_OUTPUT_DIR / rew_filename

    # Save REW file
    rew_path.write_text(rew_text, encoding="utf-8")
    logger.info(f"Saved REW EQ preset: {rew_path}")

    # Generate HQP inline syntax
    hqp_syntax = generate_hqp_pipeline_syntax(filters)

    # Generate filter summary
    summary_lines = []
    for i, f in enumerate(filters, 1):
        ftype = _normalize_filter_type(f["type"])
        freq = float(f["freq"])
        gain = float(f.get("gain", 0.0))
        q = float(f.get("q", 0.707))
        if ftype in ("HP", "LP"):
            summary_lines.append(f"  {i}. {ftype} @ {freq:.0f} Hz, Q={q:.2f}")
        else:
            summary_lines.append(f"  {i}. {ftype} @ {freq:.0f} Hz, {gain:+.1f} dB, Q={q:.2f}")
    filter_summary = "\n".join(summary_lines)

    instructions = f"""EQ Preset "{name}" generated successfully.

Filters:
{filter_summary}

HQPlayer Pipeline syntax (for Process field):
  {hqp_syntax}

REW file saved: {rew_path}
Download link (give this to the user as a clickable markdown link):
[Download {rew_filename}](/api/eq/download/{rew_filename})

To load in HQPlayer:
1. Download the .txt file by clicking the link above
2. Open HQPlayer → Menu → Matrix → Pipeline setup
3. For pipeline 1 (Left channel): click "Browse" and select the downloaded .txt file
4. For pipeline 2 (Right channel): click "Browse" and select the same .txt file
5. (Optional) You can also paste the pipeline syntax directly into the "Process" column
6. Enter a profile name in the combo box at the top (e.g. "{name}")
7. Click "Save" to save as a named profile
8. Click "OK" to apply

IMPORTANT: Do NOT enable simple Convolution (Matrix → Convolution setup) at the same time as Matrix Pipeline.

After saving, the assistant can switch to this profile using the hqplayer_set_matrix_profile command."""

    return {
        "rew_path": str(rew_path),
        "rew_filename": rew_filename,
        "rew_text": rew_text,
        "hqp_syntax": hqp_syntax,
        "filter_summary": filter_summary,
        "instructions": instructions,
        "description": description or f"EQ preset: {name}",
    }


def list_eq_presets() -> list[dict[str, str]]:
    """List all generated EQ preset files."""
    if not EQ_OUTPUT_DIR.exists():
        return []

    presets = []
    for f in sorted(EQ_OUTPUT_DIR.glob("*.txt")):
        presets.append({
            "name": f.stem,
            "filename": f.name,
            "path": str(f),
            "download_url": f"/api/eq/download/{f.name}",
        })
    return presets
