"""Regenerate the spec-attribute seed block in 001_initial.sql from the
live DB. Run on the HOST (needs the repo checkout); reads via docker exec.

Only seeded=TRUE attributes are exported — AI-proposed keys
(seeded=FALSE) must be reviewed and promoted explicitly first:
    SELECT key, applies_to FROM gear_spec_attributes WHERE NOT seeded;
    UPDATE gear_spec_attributes SET seeded=TRUE WHERE key IN (...);
This gate exists because the seed block silently minted unreviewed
keys as curated TWICE before this script existed.

001 is CRLF — the block is patched byte-wise, never text-mode.
"""
import re
import subprocess
import sys

INNER = r"""
from db_pool import db_query
rows = db_query('''SELECT id::text AS id, key, label, description, unit,
                          value_type::text AS vt, enum_values, applies_to
                   FROM gear_spec_attributes WHERE seeded ORDER BY key''')
def q(s):
    return chr(39) + s.replace(chr(39), chr(39)*2) + chr(39) if s is not None else 'NULL'
def arr(x):
    return 'ARRAY[' + ','.join(q(i) for i in x) + ']' if x else 'NULL'
print('SEEDFILE-START')
print('-- Canonical spec-attribute seed (regenerated by scripts/regen_attr_seed.py')
print('-- from the live curated catalog; AI additions land seeded=FALSE pending review).')
print('INSERT INTO gear_spec_attributes (id, key, label, description, unit, value_type, enum_values, applies_to, seeded) VALUES')
body = []
for r in rows:
    body.append("    ('%s', %s, %s, %s, %s, %s::spec_value_type, %s, %s, TRUE)" % (
        r['id'], q(r['key']), q(r['label']), q(r['description']), q(r['unit']),
        q(r['vt']), arr(r['enum_values']), arr(r['applies_to'])))
print(',\n'.join(body))
print('ON CONFLICT (key) DO NOTHING;')
"""

raw = subprocess.run(
    ["docker", "exec", "-e", "PYTHONPATH=/app", "-w", "/app",
     "sautium-backend", "python", "-c", INNER],
    capture_output=True, text=True, check=True).stdout
seed = raw.split("SEEDFILE-START\n", 1)[1].encode().replace(b"\n", b"\r\n")

path = "desktop/migrations/001_initial.sql"
data = open(path, "rb").read()
start = data.index(b"-- Canonical spec-attribute seed")
end = data.index(b"ON CONFLICT (key) DO NOTHING;\r\n", start) \
    + len(b"ON CONFLICT (key) DO NOTHING;\r\n")
open(path, "wb").write(data[:start] + seed + data[end:])
n = len(re.findall(rb"::spec_value_type", seed))
print(f"seed refreshed: {n} curated attributes", file=sys.stderr)
