"""
Configuration manager for Music AI DJ desktop launcher.

Reads/writes config from %APPDATA%/MusicAIDJ/config.json.
Generates .env file for the backend process.
"""

import json
import logging
import os
import secrets
import sys
from pathlib import Path
from typing import Any, Optional

logger = logging.getLogger(__name__)

# Default config schema version
CONFIG_VERSION = 1

DEFAULT_CONFIG = {
    "version": CONFIG_VERSION,
    "music_path": "",
    "provider": "anthropic",
    "api_keys": {
        "anthropic": None,
        "openai": None,
    },
    "openai_compat": {
        "base_url": None,
        "api_key": None,
        "model": None,
        "name": None,
    },
    "hqplayer": {
        "enabled": True,
        "host": "localhost",
        "port": 4321,
    },
    "ports": {
        "postgres": 15432,
        "web": 18000,
        "tracker": 18765,
    },
    "install_mode": "full_gpu",
    "claude_code_available": False,
    "first_run_complete": False,
    "postgres_password": None,  # auto-generated on first run
    "lastfm": {
        "api_key": None,
        "api_secret": None,
        "username": None,
        "session_key": None,
    },
    "p2p": {
        "enabled": False,
        "node_name": None,
        "listen_port": 19000,
    },
}


def get_config_dir() -> Path:
    """Get the config directory path (%APPDATA%/MusicAIDJ on Windows)."""
    if sys.platform == "win32":
        base = Path(os.environ.get("APPDATA", Path.home() / "AppData" / "Roaming"))
    else:
        base = Path(os.environ.get("XDG_CONFIG_HOME", Path.home() / ".config"))
    config_dir = base / "MusicAIDJ"
    config_dir.mkdir(parents=True, exist_ok=True)
    return config_dir


def get_config_path() -> Path:
    """Get the config file path."""
    return get_config_dir() / "config.json"


def get_data_dir() -> Path:
    """Get the data directory (for PostgreSQL data, cache, etc.)."""
    if sys.platform == "win32":
        base = Path(os.environ.get("LOCALAPPDATA", Path.home() / "AppData" / "Local"))
    else:
        base = Path(os.environ.get("XDG_DATA_HOME", Path.home() / ".local" / "share"))
    data_dir = base / "MusicAIDJ"
    data_dir.mkdir(parents=True, exist_ok=True)
    return data_dir


def load_config() -> dict:
    """Load config from disk, merging with defaults for any missing keys."""
    config_path = get_config_path()

    if config_path.exists():
        try:
            with open(config_path, "r", encoding="utf-8") as f:
                saved = json.load(f)
            config = _deep_merge(DEFAULT_CONFIG.copy(), saved)
        except (json.JSONDecodeError, OSError) as e:
            logger.error(f"Failed to load config: {e}")
            config = DEFAULT_CONFIG.copy()
    else:
        config = DEFAULT_CONFIG.copy()

    # Auto-generate postgres password if not set
    if not config.get("postgres_password"):
        config["postgres_password"] = secrets.token_urlsafe(16)
        save_config(config)

    return config


def save_config(config: dict) -> None:
    """Save config to disk."""
    config_path = get_config_path()
    try:
        with open(config_path, "w", encoding="utf-8") as f:
            json.dump(config, f, indent=2, ensure_ascii=False)
        logger.info(f"Config saved to {config_path}")
    except OSError as e:
        logger.error(f"Failed to save config: {e}")
        raise


def update_config(updates: dict) -> dict:
    """Load config, apply updates, save, and return the updated config."""
    config = load_config()
    config = _deep_merge(config, updates)
    save_config(config)
    return config


def generate_env_file(config: dict, env_path: Path) -> None:
    """
    Generate a .env file for the backend based on current config.

    Key differences from Docker:
    - POSTGRES_HOST = localhost (not 'postgres')
    - MUSIC_LIBRARY_PATH = native Windows path (not '/music')
    - HQPLAYER_HOST = localhost (not 'host.docker.internal')
    - TRACKER_URL = http://localhost:{port} (not 'http://playback-tracker:8765')
    """
    hqp = config.get("hqplayer", {})
    ports = config.get("ports", {})
    lastfm = config.get("lastfm", {})
    api_keys = config.get("api_keys", {})
    compat = config.get("openai_compat", {})

    lines = [
        "# Auto-generated by Music AI DJ Launcher",
        "# Do not edit manually — changes will be overwritten",
        "",
        "# Database",
        f"POSTGRES_HOST=localhost",
        f"POSTGRES_PORT={ports.get('postgres', 5432)}",
        f"POSTGRES_DB=music_ai",
        f"POSTGRES_USER=musicai",
        f"POSTGRES_PASSWORD={config.get('postgres_password', 'changeme')}",
        "",
        "# Music Library",
        f"MUSIC_LIBRARY_PATH={config.get('music_path', '')}",
        "",
        "# HQPlayer",
        f"HQPLAYER_HOST={hqp.get('host', 'localhost')}",
        f"HQPLAYER_PORT={hqp.get('port', 4321)}",
        f"HQPLAYER_ENABLED={'true' if hqp.get('enabled') else 'false'}",
        f"TRACKER_URL=http://localhost:{ports.get('tracker', 8765)}",
        "",
        "# AI Providers",
        f"DEFAULT_PROVIDER={config.get('provider', 'anthropic')}",
        f"ANTHROPIC_API_KEY={api_keys.get('anthropic') or ''}",
        f"OPENAI_API_KEY={api_keys.get('openai') or ''}",
        "",
        "# OpenAI-compatible endpoint",
        f"OPENAI_COMPAT_BASE_URL={compat.get('base_url') or ''}",
        f"OPENAI_COMPAT_API_KEY={compat.get('api_key') or ''}",
        f"OPENAI_COMPAT_MODEL={compat.get('model') or ''}",
        f"OPENAI_COMPAT_NAME={compat.get('name') or ''}",
        "",
        "# Claude Code",
        f"CLAUDE_CODE_ENABLED={'true' if config.get('claude_code_available') and config.get('provider') == 'claude_code' else 'false'}",
        "",
        "# Last.fm",
        f"LASTFM_API_KEY={lastfm.get('api_key') or ''}",
        f"LASTFM_API_SECRET={lastfm.get('api_secret') or ''}",
        f"LASTFM_USERNAME={lastfm.get('username') or ''}",
        f"LASTFM_SESSION_KEY={lastfm.get('session_key') or ''}",
        "",
        "# Application",
        "LOG_LEVEL=INFO",
        "CUDA_VISIBLE_DEVICES=0",
        "",
    ]

    try:
        with open(env_path, "w", encoding="utf-8") as f:
            f.write("\n".join(lines))
        logger.info(f"Generated .env at {env_path}")
    except OSError as e:
        logger.error(f"Failed to generate .env: {e}")
        raise


def generate_mcp_config(config: dict, output_path: Path) -> None:
    """Generate MCP config (mcp-windows.json) for Claude Code with localhost values."""
    ports = config.get("ports", {})
    hqp = config.get("hqplayer", {})

    mcp_config = {
        "mcpServers": {
            "postgres": {
                "command": "npx",
                "args": ["-y", "postgres-mcp-server"],
                "env": {
                    "DB_HOST": "localhost",
                    "DB_PORT": str(ports.get("postgres", 5432)),
                    "DB_USER": "musicai",
                    "DB_PASSWORD": config.get("postgres_password", "changeme"),
                    "DB_NAME": "music_ai",
                    "DB_SSL": "false",
                },
            },
            "hqplayer": {
                "command": "python",
                "args": [str(output_path.parent / "mcp" / "hqplayer_server.py")],
                "env": {
                    "DB_HOST": "localhost",
                    "DB_PORT": str(ports.get("postgres", 5432)),
                    "DB_USER": "musicai",
                    "DB_PASSWORD": config.get("postgres_password", "changeme"),
                    "DB_NAME": "music_ai",
                    "HQPLAYER_HOST": hqp.get("host", "localhost"),
                    "HQPLAYER_PORT": str(hqp.get("port", 4321)),
                    "BACKEND_URL": f"http://localhost:{ports.get('web', 8000)}",
                    "TRACKER_URL": f"http://localhost:{ports.get('tracker', 8765)}",
                },
            },
        }
    }

    try:
        with open(output_path, "w", encoding="utf-8") as f:
            json.dump(mcp_config, f, indent=2)
        logger.info(f"Generated MCP config at {output_path}")
    except OSError as e:
        logger.error(f"Failed to generate MCP config: {e}")
        raise


def _deep_merge(base: dict, override: dict) -> dict:
    """Deep merge override into base, returning a new dict."""
    result = base.copy()
    for key, value in override.items():
        if key in result and isinstance(result[key], dict) and isinstance(value, dict):
            result[key] = _deep_merge(result[key], value)
        else:
            result[key] = value
    return result
